### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by brey** [tomsail/telemac-conda#19]
I have pushed the `osx` branch.

For some reason the `conda_build_config.yaml` configuration is not working. I have opened an issue here https://github.com/conda/conda-build/issues/4948.

Please test it on linux and then merge. This way we can have a new release and test the proper recipe with the `url`.

@pmav99 @tomsail

**Comment by tomsail** [comment]
ok it worked. added a few fixes also. Shall I wait for the issue on conda to merge?

**Comment by brey** [comment]
It just occurred to me that the osx configuration is using a hardcoded `gfort-mpich` path but we can compile with both `mpich` and `openmpi`. So we should generalise. 

BTW, credit goes to this post: http://www.opentelemac.org/index.php/assistance/forum5/12-linux-version/14043-my-installation-on-macos-using-homebrew

**Comment by tomsail** [comment]
test passed and merged with [pull request #20](https://github.com/tomsail/telemac-conda/pull/20)
Also: 
* changed [HOMETEL/scripts/postel/plot2.py](https://github.com/tomsail/telemac-conda/pull/20/commits/700539feca2a1672b04f8a62841861a9a85fa293) for Hermes Support 
* unpinned python version and reverted to numpy 1.21.6 for HERMES
